SEARCH_CR = (
    ('countryAF', 'Afghanistan'),
    ('countryAL', 'Albania'),
    ('countryDZ', 'Algeria'),
    ('countryAS', 'American Samoa'),
    ('countryAD', 'Andorra'),
    ('countryAO', 'Angola'),
    ('countryAI', 'Anguilla'),
    ('countryAQ', 'Antarctica'),
    ('countryAG', 'Antigua and Barbuda'),
    ('countryAR', 'Argentina'),
    ('countryAM', 'Armenia'),
    ('countryAW', 'Aruba'),
    ('countryAU', 'Australia'),
    ('countryAT', 'Austria'),
    ('countryAZ', 'Azerbaijan'),
    ('countryBS', 'Bahamas'),
    ('countryBH', 'Bahrain'),
    ('countryBD', 'Bangladesh'),
    ('countryBB', 'Barbados'),
    ('countryBY', 'Belarus'),
    ('countryBE', 'Belgium'),
    ('countryBZ', 'Belize'),
    ('countryBJ', 'Benin'),
    ('countryBM', 'Bermuda'),
    ('countryBT', 'Bhutan'),
    ('countryBO', 'Bolivia'),
    ('countryBA', 'Bosnia and Herzegovina'),
    ('countryBW', 'Botswana'),
    ('countryBV', 'Bouvet Island'),
    ('countryBR', 'Brazil'),
    ('countryIO', 'British Indian Ocean Territory'),
    ('countryBN', 'Brunei Darussalam'),
    ('countryBG', 'Bulgaria'),
    ('countryBF', 'Burkina Faso'),
    ('countryBI', 'Burundi'),
    ('countryKH', 'Cambodia'),
    ('countryCM', 'Cameroon'),
    ('countryCA', 'Canada'),
    ('countryCV', 'Cape Verde'),
    ('countryKY', 'Cayman Islands'),
    ('countryCF', 'Central African Republic'),
    ('countryTD', 'Chad'),
    ('countryCL', 'Chile'),
    ('countryCN', 'China'),
    ('countryCX', 'Christmas Island'),
    ('countryCC', 'Cocos (Keeling) Islands'),
    ('countryCO', 'Colombia'),
    ('countryKM', 'Comoros'),
    ('countryCG', 'Congo'),
    ('countryCD', 'Congo, the Democratic Republic of the'),
    ('countryCK', 'Cook Islands'),
    ('countryCR', 'Costa Rica'),
    ('countryCI', "Cote D'ivoire"),
    ('countryHR', 'Croatia (Hrvatska)'),
    ('countryCU', 'Cuba'),
    ('countryCY', 'Cyprus'),
    ('countryCZ', 'Czech Republic'),
    ('countryDK', 'Denmark'),
    ('countryDJ', 'Djibouti'),
    ('countryDM', 'Dominica'),
    ('countryDO', 'Dominican Republic'),
    ('countryTP', 'East Timor'),
    ('countryEC', 'Ecuador'),
    ('countryEG', 'Egypt'),
    ('countrySV', 'El Salvador'),
    ('countryGQ', 'Equatorial Guinea'),
    ('countryER', 'Eritrea'),
    ('countryEE', 'Estonia'),
    ('countryET', 'Ethiopia'),
    ('countryEU', 'European Union'),
    ('countryFK', 'Falkland Islands (Malvinas)'),
    ('countryFO', 'Faroe Islands'),
    ('countryFJ', 'Fiji'),
    ('countryFI', 'Finland'),
    ('countryFR', 'France'),
    ('countryFX', 'France, Metropolitan'),
    ('countryGF', 'French Guiana'),
    ('countryPF', 'French Polynesia'),
    ('countryTF', 'French Southern Territories'),
    ('countryGA', 'Gabon'),
    ('countryGM', 'Gambia'),
    ('countryGE', 'Georgia'),
    ('countryDE', 'Germany'),
    ('countryGH', 'Ghana'),
    ('countryGI', 'Gibraltar'),
    ('countryGR', 'Greece'),
    ('countryGL', 'Greenland'),
    ('countryGD', 'Grenada'),
    ('countryGP', 'Guadeloupe'),
    ('countryGU', 'Guam'),
    ('countryGT', 'Guatemala'),
    ('countryGN', 'Guinea'),
    ('countryGW', 'Guinea-Bissau'),
    ('countryGY', 'Guyana'),
    ('countryHT', 'Haiti'),
    ('countryHM', 'Heard Island and Mcdonald Islands'),
    ('countryVA', 'Holy See (Vatican City State)'),
    ('countryHN', 'Honduras'),
    ('countryHK', 'Hong Kong'),
    ('countryHU', 'Hungary'),
    ('countryIS', 'Iceland'),
    ('countryIN', 'India'),
    ('countryID', 'Indonesia'),
    ('countryIR', 'Iran, Islamic Republic of'),
    ('countryIQ', 'Iraq'),
    ('countryIE', 'Ireland'),
    ('countryIL', 'Israel'),
    ('countryIT', 'Italy'),
    ('countryJM', 'Jamaica'),
    ('countryJP', 'Japan'),
    ('countryJO', 'Jordan'),
    ('countryKZ', 'Kazakhstan'),
    ('countryKE', 'Kenya'),
    ('countryKI', 'Kiribati'),
    ('countryKP', "Korea, Democratic People's Republic of"),
    ('countryKR', 'Korea, Republic of'),
    ('countryKW', 'Kuwait'),
    ('countryKG', 'Kyrgyzstan'),
    ('countryLA', "Lao People's Democratic Republic"),
    ('countryLV', 'Latvia'),
    ('countryLB', 'Lebanon'),
    ('countryLS', 'Lesotho'),
    ('countryLR', 'Liberia'),
    ('countryLY', 'Libyan Arab Jamahiriya'),
    ('countryLI', 'Liechtenstein'),
    ('countryLT', 'Lithuania'),
    ('countryLU', 'Luxembourg'),
    ('countryMO', 'Macao'),
    ('countryMK', 'Macedonia, the Former Yugosalv Republic of'),
    ('countryMG', 'Madagascar'),
    ('countryMW', 'Malawi'),
    ('countryMY', 'Malaysia'),
    ('countryMV', 'Maldives'),
    ('countryML', 'Mali'),
    ('countryMT', 'Malta'),
    ('countryMH', 'Marshall Islands'),
    ('countryMQ', 'Martinique'),
    ('countryMR', 'Mauritania'),
    ('countryMU', 'Mauritius'),
    ('countryYT', 'Mayotte'),
    ('countryMX', 'Mexico'),
    ('countryFM', 'Micronesia, Federated States of'),
    ('countryMD', 'Moldova, Republic of'),
    ('countryMC', 'Monaco'),
    ('countryMN', 'Mongolia'),
    ('countryMS', 'Montserrat'),
    ('countryMA', 'Morocco'),
    ('countryMZ', 'Mozambique'),
    ('countryMM', 'Myanmar'),
    ('countryNA', 'Namibia'),
    ('countryNR', 'Nauru'),
    ('countryNP', 'Nepal'),
    ('countryNL', 'Netherlands'),
    ('countryAN', 'Netherlands Antilles'),
    ('countryNC', 'New Caledonia'),
    ('countryNZ', 'New Zealand'),
    ('countryNI', 'Nicaragua'),
    ('countryNE', 'Niger'),
    ('countryNG', 'Nigeria'),
    ('countryNU', 'Niue'),
    ('countryNF', 'Norfolk Island'),
    ('countryMP', 'Northern Mariana Islands'),
    ('countryNO', 'Norway'),
    ('countryOM', 'Oman'),
    ('countryPK', 'Pakistan'),
    ('countryPW', 'Palau'),
    ('countryPS', 'Palestinian Territory'),
    ('countryPA', 'Panama'),
    ('countryPG', 'Papua New Guinea'),
    ('countryPY', 'Paraguay'),
    ('countryPE', 'Peru'),
    ('countryPH', 'Philippines'),
    ('countryPN', 'Pitcairn'),
    ('countryPL', 'Poland'),
    ('countryPT', 'Portugal'),
    ('countryPR', 'Puerto Rico'),
    ('countryQA', 'Qatar'),
    ('countryRE', 'Reunion'),
    ('countryRO', 'Romania'),
    ('countryRU', 'Russian Federation'),
    ('countryRW', 'Rwanda'),
    ('countrySH', 'Saint Helena'),
    ('countryKN', 'Saint Kitts and Nevis'),
    ('countryLC', 'Saint Lucia'),
    ('countryPM', 'Saint Pierre and Miquelon'),
    ('countryVC', 'Saint Vincent and the Grenadines'),
    ('countryWS', 'Samoa'),
    ('countrySM', 'San Marino'),
    ('countryST', 'Sao Tome and Principe'),
    ('countrySA', 'Saudi Arabia'),
    ('countrySN', 'Senegal'),
    ('countryCS', 'Serbia and Montenegro'),
    ('countrySC', 'Seychelles'),
    ('countrySL', 'Sierra Leone'),
    ('countrySG', 'Singapore'),
    ('countrySK', 'Slovakia'),
    ('countrySI', 'Slovenia'),
    ('countrySB', 'Solomon Islands'),
    ('countrySO', 'Somalia'),
    ('countryZA', 'South Africa'),
    ('countryGS', 'South Georgia and the South Sandwich Islands'),
    ('countryES', 'Spain'),
    ('countryLK', 'Sri Lanka'),
    ('countrySD', 'Sudan'),
    ('countrySR', 'Suriname'),
    ('countrySJ', 'Svalbard and Jan Mayen'),
    ('countrySZ', 'Swaziland'),
    ('countrySE', 'Sweden'),
    ('countryCH', 'Switzerland'),
    ('countrySY', 'Syrian Arab Republic'),
    ('countryTW', 'Taiwan, Province of China'),
    ('countryTJ', 'Tajikistan'),
    ('countryTZ', 'Tanzania, United Republic of'),
    ('countryTH', 'Thailand'),
    ('countryTG', 'Togo'),
    ('countryTK', 'Tokelau'),
    ('countryTO', 'Tonga'),
    ('countryTT', 'Trinidad and Tobago'),
    ('countryTN', 'Tunisia'),
    ('countryTR', 'Turkey'),
    ('countryTM', 'Turkmenistan'),
    ('countryTC', 'Turks and Caicos Islands'),
    ('countryTV', 'Tuvalu'),
    ('countryUG', 'Uganda'),
    ('countryUA', 'Ukraine'),
    ('countryAE', 'United Arab Emirates'),
    ('countryUK', 'United Kingdom'),
    ('countryUS', 'United States'),
    ('countryUM', 'United States Minor Outlying Islands'),
    ('countryUY', 'Uruguay'),
    ('countryUZ', 'Uzbekistan'),
    ('countryVU', 'Vanuatu'),
    ('countryVE', 'Venezuela'),
    ('countryVN', 'Vietnam'),
    ('countryVG', 'Virgin Islands, British'),
    ('countryVI', 'Virgin Islands, U.S.'),
    ('countryWF', 'Wallis and Futuna'),
    ('countryEH', 'Western Sahara'),
    ('countryYE', 'Yemen'),
    ('countryYU', 'Yugoslavia'),
    ('countryZM', 'Zambia'),
    ('countryZW', 'Zimbabwe'),
)
