# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxy',
            old_name='connection_count',
            new_name='scraper_count',
        ),
    ]
