# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20160302_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxy',
            options={'ordering': ['-date_updated'], 'verbose_name_plural': 'proxies'},
        ),
    ]
