# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20160302_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlesearch',
            options={'ordering': ['-date_updated'], 'verbose_name_plural': 'google searches'},
        ),
        migrations.AddField(
            model_name='googlesearch',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 2, 20, 25, 54, 91843, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googlesearch',
            name='success',
            field=models.NullBooleanField(),
        ),
    ]
