# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20160302_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlelink',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterModelOptions(
            name='googlepage',
            options={'ordering': ['-date_added']},
        ),
    ]
