# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20160302_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='region',
        ),
        migrations.AddField(
            model_name='proxy',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
