# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 21:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_proxy_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='speed',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
