# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 21:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20160302_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googlelink',
            options={},
        ),
        migrations.AlterModelOptions(
            name='googlepage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='googlesearch',
            options={'verbose_name_plural': 'google searches'},
        ),
        migrations.AlterModelOptions(
            name='proxy',
            options={'verbose_name_plural': 'proxies'},
        ),
        migrations.AlterModelOptions(
            name='useragent',
            options={},
        ),
    ]
