# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_auto_20160303_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='city',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='longitude',
        ),
    ]
