# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-06 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_auto_20160306_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlesearch',
            name='result_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
